#  20. Menggabungkan (merge) dua `DataFrame` secara berdampingan

## Import module

In [7]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.1.4
1.26.4

## Persiapan `DataFrame`

In [13]:
n_rows = 5
n_cols = 2
cols1 = list("AB")

df1 = pd.DataFrame(np.random.randint(1,5,size=(n_rows,n_cols)),columns=cols1)
df1

   A  B
0  2  3
1  1  4
2  2  4
3  1  1
4  2  4

In [15]:
cols2 = list("CD")

df2 = pd.DataFrame(np.random.randint(1,10,size=(n_rows,n_cols)),columns=cols2)
df2

   C  D
0  7  3
1  7  9
2  3  8
3  1  7
4  3  5

## Menggabungkan (merge) dua `DataFrame` secara berdampingan

In [19]:
df = pd.merge(df1,df2,left_index=True,right_index=True)
df

   A  B  C  D
0  2  3  7  3
1  1  4  7  9
2  2  4  3  8
3  1  1  1  7
4  2  4  3  5