# 44. Menata ulang penempatan kolom `DataFrame`

# Import modules

In [5]:
import pandas as pd
import numpy as np

# Persiapan `DataFrame`

In [8]:
n_rows = 5
n_cols = 5
cols = list("ABCDE")

df = pd.DataFrame(np.random.randint(1,10,size=(n_rows,n_cols)),columns=cols)
df

   A  B  C  D  E
0  9  4  6  4  9
1  1  4  5  9  8
2  4  3  4  7  2
3  5  6  5  9  5
4  8  4  4  1  9

# Menata ulang penempatan kolom pada `DataFrame`

In [11]:
df[["D","C","A","E","B"]]

   D  C  A  E  B
0  4  6  9  9  4
1  9  5  1  8  4
2  7  4  4  2  3
3  9  5  5  5  6
4  1  4  8  9  4

In [13]:
df

   A  B  C  D  E
0  9  4  6  4  9
1  1  4  5  9  8
2  4  3  4  7  2
3  5  6  5  9  5
4  8  4  4  1  9

In [15]:
df = df[["D","C","A","E","B"]]
df

   D  C  A  E  B
0  4  6  9  9  4
1  9  5  1  8  4
2  7  4  4  2  3
3  9  5  5  5  6
4  1  4  8  9  4