# 19. Formatting tampilan `DataFrame`

In [3]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [5]:
n_rows = 5
n_cols = 3
cols = ["tanggal","omset","operasional"]

df = pd.DataFrame(np.random.randint(1,20,size=(n_rows,n_cols)),columns=cols)

df["tanggal"] = pd.date_range("1/1/2000",periods=n_rows)
df

     tanggal  omset  operasional
0 2000-01-01     15            9
1 2000-01-02     16           19
2 2000-01-03     14           19
3 2000-01-04     19            3
4 2000-01-05     13           15

In [6]:
df["omset"] = df["omset"] * 100_000
df["operasional"] = df["operasional"] * 10_000
df

     tanggal    omset  operasional
0 2000-01-01  1500000        90000
1 2000-01-02  1600000       190000
2 2000-01-03  1400000       190000
3 2000-01-04  1900000        30000
4 2000-01-05  1300000       150000

## Melakukan formatting tampilan `DataFrame`

In [8]:
formatku = {
    "tanggal":"{:%d/%m/%y}",
    "omset":"Rp. {:,}",
    "operasional":"Rp. {:,}"
}

laporan = df.style.format(formatku)
laporan

In [9]:
type(laporan)

pandas.io.formats.style.Styler

In [10]:
laporan.hide()

In [11]:
laporan.set_caption("Data omset dan operasional")

In [12]:
laporan.highlight_min("omset",color="pink")
laporan.highlight_max("omset",color="lightgreen")

laporan.highlight_min("operasional",color="lightblue")
laporan.highlight_max("operasional",color="grey")