# 9. Membagi `DataFrame` menjadi dua secara acak

## Import packages

In [1]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [2]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1,10,size=(n_rows,n_cols)),columns=cols)
df

   A  B  C  D  E
0  2  1  5  2  6
1  3  4  1  4  4
2  7  3  6  3  8
3  5  9  3  1  4
4  5  3  8  5  8
5  5  6  2  2  6
6  4  9  6  8  2
7  7  9  8  9  5
8  3  6  6  3  2
9  7  6  2  4  5

In [4]:
print(f'{df.shape=}')

df.shape=(10, 5)

## Membagi `DataFrame` menjadi dua secara acak berdasarkan proporsi tertentu

In [3]:
proporsi = 0.7
df_1 = df.sample(frac=proporsi)
df_2 = df.drop(df_1.index)

print(f'{df_1.shape=}')
print(f'{df_2.shape=}')

df_1.shape=(7, 5)
df_2.shape=(3, 5)

In [9]:
df_1.reset_index(drop=True)

   A  B  C  D  E
0  5  3  8  5  8
1  2  1  5  2  6
2  3  4  1  4  4
3  7  6  2  4  5
4  7  3  6  3  8
5  3  6  6  3  2
6  5  9  3  1  4

In [10]:
df_2

   A  B  C  D  E
5  5  6  2  2  6
6  4  9  6  8  2
7  7  9  8  9  5