# 5. Membalik urutan baris dan kolom pada `DataFrame`

## Import packages

In [1]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [3]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1,5,size=(n_rows,n_cols)),columns=cols)
df

   A  B  C  D  E
0  3  4  1  3  3
1  2  2  3  2  2
2  3  1  1  3  1
3  4  1  2  2  3
4  1  2  4  1  3

## Membalik urutan kolom

In [4]:
df.loc[:,::-1]

   E  D  C  B  A
0  3  3  1  4  3
1  2  2  3  2  2
2  1  3  1  1  3
3  3  2  2  1  4
4  3  1  4  2  1

## Membalik urutan baris

In [5]:
df.loc[::-1]

   A  B  C  D  E
4  1  2  4  1  3
3  4  1  2  2  3
2  3  1  1  3  1
1  2  2  3  2  2
0  3  4  1  3  3

# Membalik urutan baris dan melaukan penyesuaian index

In [6]:
df.loc[::-1].reset_index(drop=True)

   A  B  C  D  E
0  1  2  4  1  3
1  4  1  2  2  3
2  3  1  1  3  1
3  2  2  3  2  2
4  3  4  1  3  3