# 27. Fungsi agregasi first dan last pada Python Pandas

## Import module

In [7]:
import pandas as pd

## Persiapan `DataFrame`

In [9]:
data = {
    "Dokter":["Budi","Wati","Iwan","Budi","Budi","Wati"],
    "Pasien":["Abdul","Rahmat","Asep","Joko","Wiwin","Lisa"]
}

df = pd.DataFrame(data)
df

  Dokter  Pasien
0   Budi   Abdul
1   Wati  Rahmat
2   Iwan    Asep
3   Budi    Joko
4   Budi   Wiwin
5   Wati    Lisa

## Mengenal fungsi agregasi `first()` dan `last()`

In [18]:
# Menghitung jumlah total pasien untuk setiap masing-masing dokter
df.groupby("Dokter")["Pasien"].count().to_frame()

        Pasien
Dokter
Budi         3
Iwan         1
Wati         2

In [22]:
# Menampilkan nama pasien pertama untuk masing-masing dokter
df.groupby("Dokter")["Pasien"].first().to_frame()

        Pasien
Dokter
Budi     Abdul
Iwan      Asep
Wati    Rahmat

In [26]:
# Menampilkan nama pasien terakhir untuk masing-masing dokter
df.groupby("Dokter")["Pasien"].last().to_frame()

       Pasien
Dokter
Budi    Wiwin
Iwan     Asep
Wati     Lisa