# 14. Menggabungkan dua Pandas `DataFrame`

In [1]:
import pandas as pd
import numpy as np

In [2]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1,5,size=(n_rows,n_cols)),columns=cols)
df

   A  B  C  D  E
0  3  1  1  1  1
1  4  1  3  1  3
2  4  3  4  4  2
3  2  1  3  3  3
4  3  2  2  3  4

In [3]:
df1 = df.copy(deep=True)
df1 = df1.drop([1,4])
df1

   A  B  C  D  E
0  3  1  1  1  1
2  4  3  4  4  2
3  2  1  3  3  3

In [5]:
df2 = df.copy(deep=True)
df2 = df2.drop([0,3])
df2

   A  B  C  D  E
1  4  1  3  1  3
2  4  3  4  4  2
4  3  2  2  3  4

## Menggabungkan dua `DataFrame`

In [6]:
df_inner = pd.merge(df1,df2,how='inner')
df_inner

   A  B  C  D  E
0  4  3  4  4  2

In [8]:
df_outer = pd.merge(df1,df2,how='outer')
df_outer

   A  B  C  D  E
0  2  1  3  3  3
1  3  1  1  1  1
2  3  2  2  3  4
3  4  1  3  1  3
4  4  3  4  4  2