# 31. Tipe data ordinal pada pandas `DataFrame`

## Import module

In [4]:
import pandas as pd

## Persiapan `DataFrame`

In [6]:
data = {
    "Nama":["Ali","Gerry","Mogi","Sampi"],
    "Tingkat_kepuasaan":["Sangat memuaskaan","Memuaskaan","Cukup","Tidak memuaskaan"]
}

df = pd.DataFrame(data)
df

    Nama  Tingkat_kepuasaan
0    Ali  Sangat memuaskaan
1  Gerry         Memuaskaan
2   Mogi              Cukup
3  Sampi   Tidak memuaskaan

## Tipe data ordinal pada pandas

In [8]:
from pandas.api.types import CategoricalDtype

tingkat_kepuasaan = CategoricalDtype(["Tidak memuaskaan","Cukup","Memuaskaan","Sangat memuaskaan"],ordered=True)

df["Tingkat_kepuasaan"] = df["Tingkat_kepuasaan"].astype(tingkat_kepuasaan)
df

    Nama  Tingkat_kepuasaan
0    Ali  Sangat memuaskaan
1  Gerry         Memuaskaan
2   Mogi              Cukup
3  Sampi   Tidak memuaskaan

In [9]:
df.sort_values(by="Tingkat_kepuasaan",ignore_index=True)

    Nama  Tingkat_kepuasaan
0  Sampi   Tidak memuaskaan
1   Mogi              Cukup
2  Gerry         Memuaskaan
3    Ali  Sangat memuaskaan

In [10]:
df[df["Tingkat_kepuasaan"] > "Cukup"]

    Nama  Tingkat_kepuasaan
0    Ali  Sangat memuaskaan
1  Gerry         Memuaskaan