# 15. Memecah nilai string suatu kolom ke dalam beberapa kolom baru pada Pandas `DataFrame`

In [2]:
import pandas as pd

## Persiapan `DataFrame`

In [28]:
data = {
    'President\'s_name':['Bung Karno','Soeharto','Bacharuddin Jusuf Habibi','Susilo Bambang Yudhoyono','Joko Widodo'],
    'Born_Place':['Surabaya, Jawa Timur','Bantul, Yogyakarta','Bugis, Gorontalo','Pacitan, Jawa Timur','Surakarta, Jawa Tengah']
}

df = pd.DataFrame(data)
df

           President's_name              Born_Place
0                Bung Karno    Surabaya, Jawa Timur
1                  Soeharto      Bantul, Yogyakarta
2  Bacharuddin Jusuf Habibi        Bugis, Gorontalo
3  Susilo Bambang Yudhoyono     Pacitan, Jawa Timur
4               Joko Widodo  Surakarta, Jawa Tengah

## Memecah nama Kota dan Provinsi

In [35]:
df[['City','Province']] = df['Born_Place'].str.split(',',expand=True)
df

           President's_name              Born_Place       City      Province
0                Bung Karno    Surabaya, Jawa Timur   Surabaya    Jawa Timur
1                  Soeharto      Bantul, Yogyakarta     Bantul    Yogyakarta
2  Bacharuddin Jusuf Habibi        Bugis, Gorontalo      Bugis     Gorontalo
3  Susilo Bambang Yudhoyono     Pacitan, Jawa Timur    Pacitan    Jawa Timur
4               Joko Widodo  Surakarta, Jawa Tengah  Surakarta   Jawa Tengah