# 50. Membuat kolom baru dengan `looping ` dan `f-string`

# Import module

In [4]:
import pandas as pd

pd.__version__

'2.2.2'

In [5]:
data = {
    "Penjual":["Bejo","Tejo","Wati","Bejo","Cecep","Tejo","Wati","Bejo"],
    "Barang":["Monitor","Monitor","Keyboard","Mouse","Keyboard","Monitor","Laptop","Monitor"]
}

df = pd.DataFrame(data)
df

  Penjual    Barang
0    Bejo   Monitor
1    Tejo   Monitor
2    Wati  Keyboard
3    Bejo     Mouse
4   Cecep  Keyboard
5    Tejo   Monitor
6    Wati    Laptop
7    Bejo   Monitor

# Membuat kolom baru dengan `for loop` dan `f-string`

In [9]:
cols = ["Penjual","Barang"]

for col in cols:
    df[f"CountSetiap{col}"] = df.groupby(col).cumcount() + 1

df

  Penjual    Barang  CountSetiapPenjual  CountSetiapBarang
0    Bejo   Monitor                   1                  1
1    Tejo   Monitor                   1                  2
2    Wati  Keyboard                   1                  1
3    Bejo     Mouse                   2                  1
4   Cecep  Keyboard                   1                  2
5    Tejo   Monitor                   2                  3
6    Wati    Laptop                   2                  1
7    Bejo   Monitor                   3                  4