# 1. Menyertakan Prefix dan Suffix pada seluruh Kolom Pandas `DataFrame`

## Import pacakges

In [3]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [6]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1,10,size=(n_rows,n_cols)),columns=cols)
df

   A  B  C  D  E
0  2  7  6  2  1
1  2  3  1  5  2
2  8  2  9  3  1
3  3  1  8  6  7
4  2  9  3  3  6

## Menyertakan prefix (string bagian depan) ke keseluruhan kolom `DataFrame`

In [9]:
df.add_prefix('Kolom_')

   Kolom_A  Kolom_B  Kolom_C  Kolom_D  Kolom_E
0        2        7        6        2        1
1        2        3        1        5        2
2        8        2        9        3        1
3        3        1        8        6        7
4        2        9        3        3        6

## Menyertakan suffix (string bagian belakang) ke keseluruhan kolom `DataFrame`

In [15]:
df.add_suffix('_field')

   A_field  B_field  C_field  D_field  E_field
0        2        7        6        2        1
1        2        3        1        5        2
2        8        2        9        3        1
3        3        1        8        6        7
4        2        9        3        3        6