# 3. Konversi tipe data String ke Numerik pada kolom `DataFrame`

## Import packages

In [4]:
import pandas as pd

## Persiapan `DataFrame`

In [9]:
data = {
    'Kolom_A':['1','2','3','4','5'],
    'Kolom_B':['1','2','3','4','Ali Ganteng']
}

df = pd.DataFrame(data)
df

  Kolom_A      Kolom_B
0       1            1
1       2            2
2       3            3
3       4            4
4       5  Ali Ganteng

In [11]:
df.dtypes

Kolom_A    object
Kolom_B    object
dtype: object

## Konversi tipe data dengan menggunakan method `.astype()`

In [14]:
df = df.astype({'Kolom_A':'int'})
df

   Kolom_A      Kolom_B
0        1            1
1        2            2
2        3            3
3        4            4
4        5  Ali Ganteng

In [16]:
df.dtypes

Kolom_A     int32
Kolom_B    object
dtype: object

## Konversi keseluruhan kolom menjadi numerik

In [19]:
df = df.apply(pd.to_numeric,errors='coerce')
df

   Kolom_A  Kolom_B
0        1      1.0
1        2      2.0
2        3      3.0
3        4      4.0
4        5      NaN