# 2. Pemilihan baris (rows selection) pada `DataFrame`

## Import packages

In [4]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [9]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1,10,size=(n_rows,n_cols)),columns=cols)
df

   A  B  C  D  E
0  4  1  9  8  5
1  7  9  8  6  9
2  6  8  2  6  1
3  7  7  3  1  9
4  8  2  5  9  1
5  7  7  5  8  7
6  7  3  5  7  3
7  9  8  1  7  6
8  7  8  5  2  5
9  7  7  7  3  2

## Rows selection menggunakan operator logika `|`

In [12]:
df[(df['A'] == 7) | (df['A'] == 8)]

   A  B  C  D  E
1  7  9  8  6  9
3  7  7  3  1  9
4  8  2  5  9  1
5  7  7  5  8  7
6  7  3  5  7  3
8  7  8  5  2  5
9  7  7  7  3  2

## Rows selection menggunakan method `.isin()`

In [15]:
df[df['A'].isin([7,8])]

   A  B  C  D  E
1  7  9  8  6  9
3  7  7  3  1  9
4  8  2  5  9  1
5  7  7  5  8  7
6  7  3  5  7  3
8  7  8  5  2  5
9  7  7  7  3  2

## Rows selection menggunakan negasi `~`

In [18]:
df[~df['A'].isin([7,8])]

   A  B  C  D  E
0  4  1  9  8  5
2  6  8  2  6  1
7  9  8  1  7  6