# 23. Seleksi baris pada `DataFrame` dengan query

## Import module

In [1]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [3]:
# Manually create a DataFrame object from a dictionary consits of a lists
n_rows = 10
n_cols = 2
cols = ["kolom_satu","kolom dua"]

df1 = pd.DataFrame(np.random.randint(1,20,size=(n_rows,n_cols)),columns=cols)
df1

   kolom_satu  kolom dua
0           3         13
1          14         16
2          19          7
3           5         16
4          17         13
5           4         11
6          11         19
7          11          2
8           1          5
9           7          3

In [7]:
# Create a backup DataFrame object
df_backup = df1.copy(deep=True)

In [9]:
# Read titanicfull.csv file and create a DataFrame
df2 = pd.read_csv("../titanicfull.csv")
df2.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

## Seleksi baris dengan `.query()`

In [11]:
df2.query("age < 18")

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
53,1,0,"Carrau, Mr. Jose Pedro",male,17.00,0,0,113059,47.1000,NaN,S
54,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
55,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
...,...,...,...,...,...,...,...,...,...,...,...
1265,3,0,"Van Impe, Miss. Catharina",female,10.00,0,2,345773,24.1500,NaN,S
1275,3,0,"Vander Planke, Mr. Leo Edmondus",male,16.00,2,0,345764,18.0000,NaN,S
1279,3,0,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,7.8542,NaN,S
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C

In [13]:
# Selecting a column without underscore using .query() method
# First technique
df1.query("`kolom dua` > 18")

   kolom_satu  kolom dua
6          11         19

In [17]:
# Second technique
df1 = df1.rename(columns={"kolom dua":"kolom_dua"})
df1.query('kolom_dua > 18')

   kolom_satu  kolom_dua
6          11         19