# 11. Seleksi kolom dan baris pada `DataFrame` menggunakan attribute `.loc`

## Import pandas package

In [1]:
import pandas as pd

## Persiapan `DataFrame`

In [2]:
df = pd.read_csv('../titanicfull.csv')
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

In [3]:
df_backup = df.copy(deep=True)

## Seleksi kolom dan baris menggunakan attribute `.loc`

In [4]:
df.loc[[0,3,4],['name','sex','age']]

                                              name     sex   age
0                    Allen, Miss. Elisabeth Walton  female  29.0
3             Allison, Mr. Hudson Joshua Creighton    male  30.0
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0

## Seleksi baris dengan kondisi

In [5]:
df = df.loc[df['age'] < 18,['name','sex','age']]
df.head()

                                   name     sex    age
1        Allison, Master. Hudson Trevor    male   0.92
2          Allison, Miss. Helen Loraine  female   2.00
53               Carrau, Mr. Jose Pedro    male  17.00
54  Carter, Master. William Thornton II    male  11.00
55            Carter, Miss. Lucile Polk  female  14.00

## Slicing `DataFrame` menggunakan attribute `.loc`

In [8]:
df = df_backup

df.loc[0:5,'survived':'age']

   survived                                             name     sex    age
0         1                    Allen, Miss. Elisabeth Walton  female  29.00
1         1                   Allison, Master. Hudson Trevor    male   0.92
2         0                     Allison, Miss. Helen Loraine  female   2.00
3         0             Allison, Mr. Hudson Joshua Creighton    male  30.00
4         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
5         1                              Anderson, Mr. Harry    male  48.00