# 18. Membentuk dummy `DataFrame` Python Pandas

In [3]:
import pandas as pd
import numpy as np

## Membentuk object `DataFrame` dari dictionary beserta dengan sekumpulan lists pada dictionary

In [5]:
data = {
    'Name':['Ali','Mogi','Gerry'],
    'Age':[21,18,17],
    'Gender':['Male','Female','Male']
}

df = pd.DataFrame(data)
df

    Name  Age  Gender
0    Ali   21    Male
1   Mogi   18  Female
2  Gerry   17    Male

## Membentuk object `DataFrame` dari `NumPy` array beserta dengan missing values (`NaN`)

In [18]:
n_rows = 10
n_cols = 5
cols = list('ABCDE')
rng = np.random.default_rng()

df = pd.DataFrame(rng.integers(1,10,size=(n_rows,n_cols)),columns=cols)
df.loc[0:5,'A'] = np.nan
df.loc[5:6,'E'] = np.nan

df

     A  B  C  D    E
0  NaN  7  1  6  5.0
1  NaN  6  9  2  1.0
2  NaN  9  9  6  5.0
3  NaN  3  5  3  8.0
4  NaN  3  1  9  4.0
5  NaN  4  2  8  NaN
6  6.0  6  6  5  NaN
7  9.0  2  1  2  7.0
8  6.0  6  4  8  3.0
9  8.0  2  4  4  2.0