# 28. Mengenal `explode` dan `implode` List pada Pandas `DataFrame`

## Import module

In [3]:
import pandas as pd

pd.__version__

'2.2.2'

In [4]:
data = {
    "Team":["Dc","Marvel"],
    "Heroes":[["Batman","Superman","Wonder Woman","Aquaman","Green Lantren","Shazam"],["Iron Man","Captain America","Ant-Man","Black Panther","Captain Marvel"]]
}

df = pd.DataFrame(data)
df

     Team                                             Heroes
0      Dc  [Batman, Superman, Wonder Woman, Aquaman, Gree...
1  Marvel  [Iron Man, Captain America, Ant-Man, Black Pan...

## Explode

In [6]:
df.explode?

Signature: df.explode(column: 'IndexLabel', ignore_index: 'bool' = False) -> 'DataFrame'
Docstring:
Transform each element of a list-like to a row, replicating index values.

Parameters
----------
column : IndexLabel
    Column(s) to explode.
    For multiple columns, specify a non-empty list with each element
    be str or tuple, and all specified columns their list-like data
    on same row of the frame must have matching length.

    .. versionadded:: 1.3.0
        Multi-column explode

ignore_index : bool, default False
    If True, the resulting index will be labeled 0, 1, …, n - 1.

Returns
-------
DataFrame
    Exploded lists to rows of the subset columns;
    index will be duplicated for these rows.

Raises
------
ValueError :
    * If columns of the frame are not unique.
    * If specified columns to explode is empty list.
    * If specified columns to explode have not matching count of
      elements rowwise in the frame.

See Also
--------
DataFrame.unstack : Pivot a level of the (necessarily hierarchical)
    index labels.
DataFrame.melt : Unpivot a DataFrame from wide format to long format.
Series.explode : Explode a DataFrame from list-like columns to long format.

Notes
-----
This routine will explode list-likes including lists, tuples, sets,
Series, and np.ndarray. The result dtype of the subset rows will
be object. Scalars will be returned unchanged, and empty list-likes will
result in a np.nan for that row. In addition, the ordering of rows in the
output will be non-deterministic when exploding sets.

Reference :ref:`the user guide <reshaping.explode>` for more examples.

Examples
--------
>>> df = pd.DataFrame({'A': [[0, 1, 2], 'foo', [], [3, 4]],
...                    'B': 1,
...                    'C': [['a', 'b', 'c'], np.nan, [], ['d', 'e']]})
>>> df
           A  B          C
0  [0, 1, 2]  1  [a, b, c]
1        foo  1        NaN
2         []  1         []
3     [3, 4]  1     [d, e]

Single-column explode.

>>> df.explode('A')
     A  B          C
0    0  1  [a, b, c]
0    1  1  [a, b, c]
0    2  1  [a, b, c]
1  foo  1        NaN
2  NaN  1         []
3    3  1     [d, e]
3    4  1     [d, e]

Multi-column explode.

>>> df.explode(list('AC'))
     A  B    C
0    0  1    a
0    1  1    b
0    2  1    c
1  foo  1  NaN
2  NaN  1  NaN
3    3  1    d
3    4  1    e
File:      c:\users\ibnua\anaconda3\lib\site-packages\pandas\core\frame.py
Type:      method

In [24]:
df1 = df.explode('Heroes')
df1

     Team           Heroes
0      Dc           Batman
0      Dc         Superman
0      Dc     Wonder Woman
0      Dc          Aquaman
0      Dc    Green Lantren
0      Dc           Shazam
1  Marvel         Iron Man
1  Marvel  Captain America
1  Marvel          Ant-Man
1  Marvel    Black Panther
1  Marvel   Captain Marvel

In [34]:
# Menggunakan parameter `ignore_index=True`
df2 = df.explode("Heroes",ignore_index=True)
df2

      Team           Heroes
0       Dc           Batman
1       Dc         Superman
2       Dc     Wonder Woman
3       Dc          Aquaman
4       Dc    Green Lantren
5       Dc           Shazam
6   Marvel         Iron Man
7   Marvel  Captain America
8   Marvel          Ant-Man
9   Marvel    Black Panther
10  Marvel   Captain Marvel

## Implode

In [30]:
d = {
    "Team":["Dc","Marvel"]
}

df3 = pd.DataFrame(d)
df3

     Team
0      Dc
1  Marvel

In [32]:
df3["Imploded"] = df1.groupby(df1.index)["Heroes"].agg(list)
df3

     Team                                           Imploded
0      Dc  [Batman, Superman, Wonder Woman, Aquaman, Gree...
1  Marvel  [Iron Man, Captain America, Ant-Man, Black Pan...