# 1. What kind of data does pandas handle?
To start working on Python pandas `DataFrame` and `Series`, we'll need to import the Python pandas package first and set the alias name for the package as `pd`.

In [1]:
# Import the package and set an alias name to pd
import pandas as pd

## What is a `DataFrame`?
`DataFrame` is a two dimensional data structure (rows and columns) that can store data of different types (including strings (objects), integers, floating point values, lists, and more) in columns.

To manually store data in a table, we'll need to create a `DataFrame`. When using Python dictionary of lists, the keys will be used as column headers and the elements (values) of each lists will be used as corresponding value rows to each column headers.

In [2]:
# Manually create a DataFrame using Python dictionary of lists

# The table (DataFrame) has 3 columns, each of them with column label. The column labels are respectively Name, Age, and Gender.

# The column Name consists of strings (objects), the column Age consits of integer numbers, and column Gender consists of strings (objects).
data = {
    'Name':['Gerry','Mogi','Sampi'],
    'Age':[18,17,16],
    'Gender':['Male','Female','Female']
}

df = pd.DataFrame(data)
df

    Name  Age  Gender
0  Gerry   18    Male
1   Mogi   17  Female
2  Sampi   16  Female

In [3]:
df.dtypes

Name      object
Age        int64
Gender    object
dtype: object

## Each column in a `DataFrame` is a `Series`
`Series` is a one dimensional data structure (rows of data) that can store data of different types (including strings (object), integers, floating point value).

To select a single column in a `DataFrame` use the column label in between square brackets `[]`. Selecting a single column of a `DataFrame` yields a `Series`.

In [4]:
# Selecting column label Age
df['Age']

0    18
1    17
2    16
Name: Age, dtype: int64

In [5]:
type(df['Age'])

pandas.core.series.Series

In [8]:
# We could also create a Series from scrath using pd.Series class
ages = pd.Series([10,11,12,13,14,15],name='Age')
ages

0    10
1    11
2    12
3    13
4    14
5    15
Name: Age, dtype: int64

## Do something with the `DataFrame` and `Series`

### `max()` method
`max()` method returns the maximum (highest) number in a `DataFrame` or `Series`.

In [9]:
# Get the maximum age of the DataFrame
df['Age'].max()

18

In [10]:
ages.max()

15

### `.describe()` method
`.describe()` method returns some basic statistics of the numerical data.

In [11]:
# Since Name and Gender columns are consists of textual data (object), by default it will be ignored.
df.describe()

        Age
count   3.0
mean   17.0
std     1.0
min    16.0
25%    16.5
50%    17.0
75%    17.5
max    18.0