# 48. Mengenal Cummulative Count dengan `cumcount()`

# Import module

In [3]:
import pandas as pd

# Persiapan `DataFrame`

In [6]:
data = {
    "Penjual":["Bejo","Tejo","Wati","Bejo","Cecep","Tejo","Wati","Bejo"],
    "Barang":["Monitor","Monitor","Keyboard","Mouse","Keyboard","Monitor","Laptop","Monitor"]
}

df = pd.DataFrame(data)
df

  Penjual    Barang
0    Bejo   Monitor
1    Tejo   Monitor
2    Wati  Keyboard
3    Bejo     Mouse
4   Cecep  Keyboard
5    Tejo   Monitor
6    Wati    Laptop
7    Bejo   Monitor

# Mengenal Cummulative count dengan `cumcount()`

In [9]:
df["count_tiap_penjual"] = df.groupby("Penjual").cumcount() + 1
df

  Penjual    Barang  count_tiap_penjual
0    Bejo   Monitor                   1
1    Tejo   Monitor                   1
2    Wati  Keyboard                   1
3    Bejo     Mouse                   2
4   Cecep  Keyboard                   1
5    Tejo   Monitor                   2
6    Wati    Laptop                   2
7    Bejo   Monitor                   3

In [11]:
df["count_tiap_barang"] = df.groupby("Barang").cumcount() + 1
df

  Penjual    Barang  count_tiap_penjual  count_tiap_barang
0    Bejo   Monitor                   1                  1
1    Tejo   Monitor                   1                  2
2    Wati  Keyboard                   1                  1
3    Bejo     Mouse                   2                  1
4   Cecep  Keyboard                   1                  2
5    Tejo   Monitor                   2                  3
6    Wati    Laptop                   2                  1
7    Bejo   Monitor                   3                  4

In [13]:
df["count_pasangan_kolom"] = df.groupby(["Penjual","Barang"]).cumcount() + 1
df

,Penjual,Barang,count_tiap_penjual,count_tiap_barang,count_pasangan_kolom
0,Bejo,Monitor,1,1,1
1,Tejo,Monitor,1,2,1
2,Wati,Keyboard,1,1,1
3,Bejo,Mouse,2,1,1
4,Cecep,Keyboard,1,2,1
5,Tejo,Monitor,2,3,2
6,Wati,Laptop,2,1,1
7,Bejo,Monitor,3,4,2