# 39. Mengacak urutan baris pada `DataFrame`

## Import modules

In [2]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [7]:
n_rows = 6
n_cols = 5
cols = list("ABCDE")

df = pd.DataFrame(np.random.randint(1,5,size=(n_rows,n_cols)),columns=cols)
df

   A  B  C  D  E
0  2  1  3  3  3
1  2  3  2  2  4
2  1  4  3  4  4
3  4  2  1  3  4
4  1  2  4  3  4
5  4  2  3  2  4

## Mengacak baris pada `DataFrame`

In [12]:
df.sample(frac=1.0,random_state=1)

   A  B  C  D  E
2  1  4  3  4  4
1  2  3  2  2  4
4  1  2  4  3  4
0  2  1  3  3  3
3  4  2  1  3  4
5  4  2  3  2  4

In [14]:
df.sample(frac=1.0,random_state=1,ignore_index=True)

   A  B  C  D  E
0  1  4  3  4  4
1  2  3  2  2  4
2  1  2  4  3  4
3  2  1  3  3  3
4  4  2  1  3  4
5  4  2  3  2  4