# 51. Seleksi baris dengan `between()`

# Import modules

In [8]:
import pandas as pd
import numpy as np

# Persiapan `DataFrame`

In [11]:
cols = 5
rows = 10
columns = list("ABCDE")

df = pd.DataFrame(np.random.randint(1,10,size=(rows,cols)),columns=columns)
df

   A  B  C  D  E
0  1  1  7  8  1
1  4  9  9  1  5
2  9  5  5  8  5
3  6  6  4  6  2
4  6  3  8  8  2
5  7  8  8  3  8
6  7  8  1  8  9
7  2  5  7  1  6
8  1  2  9  7  6
9  1  6  5  9  6

# Seleksi baris dengan `between()`

In [13]:
df[df["A"].between(2,5)]

   A  B  C  D  E
1  4  9  9  1  5
7  2  5  7  1  6

In [28]:
df[df["B"].between(2,5)]

   A  B  C  D  E
2  9  5  5  8  5
4  6  3  8  8  2
7  2  5  7  1  6
8  1  2  9  7  6